services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_video%'

  HeimrichHannot\VideoBundle\Generator\VideoGenerator:
    public: true

  HeimrichHannot\VideoBundle\Collection\VideoProviderCollection:
    public: true

  HeimrichHannot\VideoBundle\EventListener\Dca\ModifiyVideoPaletteListener:
    public: true

  HeimrichHannot\VideoBundle\Controller\:
    resource: ../../Controller/*

  HeimrichHannot\VideoBundle\EventListener\LoadDataContainerListener:
    public: true

  HeimrichHannot\VideoBundle\EventListener\ParseArticlesListener:
    public: true

  HeimrichHannot\VideoBundle\Asset\FrontendAsset:
    public: true